baseURL = "https://jonahbreslow.github.io/"
languageCode = "en-us"
title = "Jonah Breslow's Blog"
theme = "hugo-coder"


paginate = 20

# disqusShortname = 'yourDisqusShortname'

[markup.highlight]
style = "github-dark"

[params]
  author = "Jonah Breslow"
  info = "Machine Learning Engineer and Data Scientist"
  description = "Jonah Breslow's personal website"
  keywords = "blog,developer,personal,machine learning,data"
  # avatarurl = "images/avatar.jpg"
  gravatar = "jonahbreslow@gmail.com"

  since = 2023

  # enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/style.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/JonahBreslow/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/thebook0fjonah/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Contact"
  weight = 3
  url = "contact/"
